import { IntroHero } from "@/components/sections/IntroHero";
import { PersonCards } from "@/components/sections/PersonCards";
import { ConnectCta } from "@/components/sections/ConnectCta";
import { Button } from "@/components/ui/Button";
import { leadership } from "@/content/people";
import { principles } from "@/content/site";

export const metadata = { title: "About" };
export default function AboutPage() {
  return <><IntroHero title="About Us" breadcrumb="About" image="/media/hero-about.jpg" /><section className="about-overview" id="content"><div className="funds-card"><p>Our Funds Over Time</p><div><strong><sup>USD</sup>18M</strong><span>Fund I — Solidarity (2012)</span></div><div><strong><sup>FRW</sup>184bn</strong><span>Fund II — Transfer (2018)</span></div></div><div className="about-story"><h2 data-word-fill>Agaciro means dignity.</h2><p>Born from Rwanda&apos;s 2011 Umushyikirano and launched on 23 August 2012, the fund channels national savings into long-term resilience. Since 2013, Agaciro has operated as an investment company wholly owned by the Government of Rwanda under Law N° 007/2021.</p></div></section><section className="numbers-section"><h2>Agaciro in Numbers</h2><div className="number-grid"><div><strong><span data-count="456">456</span>bn</strong><span>FRW AUM</span></div><div><strong><span data-count="25">25</span>+</strong><span>Investments</span></div><div><strong><span data-count="7">7</span></strong><span>Sectors</span></div><div><strong>2012</strong><span>Launched</span></div><div><strong>14+</strong><span>Years of stewardship</span></div></div></section><section className="leadership-section"><div className="center-heading"><p>People</p><h2>Our Leadership</h2></div><PersonCards items={leadership} /><div className="split-actions"><Button href="/about/board">Full board</Button><Button href="/about/team" variant="sand">Full team</Button></div></section><section className="about-principles"><div className="section-intro"><h2>Aligned. Patient.<br /><span>Built for Rwanda.</span></h2><p data-word-fill>Governance, commercial discipline, and developmental impact work together across every investment decision.</p></div><div className="principles-list principles-list--seven">{[...principles, ["05", "Rigorous asset-level risk management"], ["06", "Independent, two-stage investment approval"], ["07", "Accountability through MINECOFIN"]].map(([n, label]) => <div key={n}><span>{n}</span><p>{label}</p></div>)}</div></section><section className="drives-section"><div><p>What Drives Us</p><h2>Building enduring value for a resilient Rwanda.</h2></div><div className="drive-cards"><article><span>01</span><h3>National purpose</h3><p>Investing savings for citizens today and generations ahead.</p></article><article><span>02</span><h3>Partner of choice</h3><p>Working with disciplined enterprises and aligned co-investors.</p></article><article><span>03</span><h3>Enduring principles</h3><p>Commercial returns, developmental impact, and clear governance.</p></article></div></section><ConnectCta /></>;
}
